//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Script/Input/InputSchemes/InputScheme.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputScheme : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputScheme()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputScheme"",
    ""maps"": [
        {
            ""name"": ""Keyboard"",
            ""id"": ""f07187b6-06b7-4380-a9a3-ec48e28769c8"",
            ""actions"": [
                {
                    ""name"": ""LeftStick"",
                    ""type"": ""Value"",
                    ""id"": ""fc971480-821e-4c8f-abe0-0e00c1076c33"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""Value"",
                    ""id"": ""ebe7463b-d35d-46de-9be4-a2f76accd960"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""8d542b8e-f39c-4a95-9844-ac70fdaf5f68"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""59a73ac4-fad7-4fc9-afea-a0a297f83d95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""15a43072-4f26-42dc-8197-96382bc83b91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""ea78272c-f7a4-4c72-bfa1-6780659bd838"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""82ca62d0-63a9-4848-a13b-d2eef2361ebe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a6a4d9e1-60e0-40db-96f3-e696465ab5d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""195fbff9-1665-4141-b3dc-c3c2643ec976"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""40ac789a-a7ec-4122-a7c1-a17a2144e999"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""f623d367-0953-4f26-ba77-d519c930a210"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""242a4b86-0f93-4c25-8224-e44e46af5c23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""78018eae-42d1-440a-bc61-d3f54e9fe764"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""c2871867-3dc8-4f3e-8735-6875a67fe16c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Circle"",
                    ""type"": ""Button"",
                    ""id"": ""ac15d4eb-fb48-4e7d-874c-2a5621594290"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""7dc8b83d-3430-4804-b8a8-28d77aecb3f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Square"",
                    ""type"": ""Button"",
                    ""id"": ""a9a6f3cc-ad47-40dd-ba15-87efc58384bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b9ddf8f1-8854-484c-acc4-d8ba5dc7bc42"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""21e3eaa8-0b05-437a-b159-57f1501ebb6d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1e0cfd74-10ef-468d-935c-3e837ed16aae"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""788a888d-df30-41b5-954e-d19c01cf72bf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""87b3a9f0-fdd9-4576-887d-d3785a6b9079"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7a4098f2-e766-4220-a6fa-39e101fc5c6b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""98507289-e39b-493c-9325-4f3e3f62c71a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cf1ce164-7686-4daf-8c87-8578d0234ce8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0ecf26e9-179c-49ee-9c3a-aaf338f3788c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""02effced-e86a-4e75-a9a4-d9225c2b1a41"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a978ac8e-725b-44a4-908d-a2b9b9596491"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e079935-055c-4ff6-b561-ec81b70629f2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7e0155e-0a5f-4077-be83-aa08d9fb6069"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a762549b-8f73-4f67-8c23-0aed4465b704"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de4ba2a6-2eeb-4511-a81d-3882949ed467"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7a5adc5-a364-49fa-9b80-d90509acd152"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a3577dc-eb3e-47a2-8669-3a4d001acb3b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf4aebf1-d3ff-41c0-9266-ca1a53f30122"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85031d29-2c01-4470-bc88-0860150c86ce"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbbb3a1d-1f22-4cbf-a8cb-d9d38f5603d2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12515cc5-e8c7-412c-8d98-ee6e91c8ca1d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98a27675-fa38-43a5-baa4-a08a60dbf63b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""746b90d8-74e4-4eed-ad76-cfa8f6c52f2e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bc9baf6-5e79-4321-956d-1134da3bc41c"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a0ea679-20eb-4f07-a4dd-af65147c4665"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DualShock4"",
            ""id"": ""7dabee2f-2747-4b58-b860-5ccc1024bb8a"",
            ""actions"": [
                {
                    ""name"": ""LeftStick"",
                    ""type"": ""Value"",
                    ""id"": ""facf72db-a12b-4b91-b604-3dec8851abc7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""Value"",
                    ""id"": ""8532285c-86f0-4318-888f-e44a6e9fa891"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""095f8ee9-f917-4c88-b206-0ae37aeab774"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""2640b43f-0adc-4a5c-a693-b4977e796e55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""e1834f1c-0d65-4eb0-9f2b-3e3f3eba8e5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""e687bc14-dff8-423b-a483-b8ec851f8ef7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""ac076497-81bd-404f-b4e9-5c42f2dd0349"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1eba4bc6-37d9-446b-8fcd-797e17f91b4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""3fa1ed0b-924b-4289-85e5-df07f15626b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L1"",
                    ""type"": ""Button"",
                    ""id"": ""842fba86-021b-41de-8c92-b0d459f08b9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""L2"",
                    ""type"": ""Button"",
                    ""id"": ""11ee8199-1af6-46a7-9e20-6e19a2b0e51b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R1"",
                    ""type"": ""Button"",
                    ""id"": ""96f3e58f-a775-400b-879c-b78f0bdbb58c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""R2"",
                    ""type"": ""Button"",
                    ""id"": ""1585d025-14cf-4c72-bd47-3c4a141b592d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""de14afdd-d9df-47f9-95ee-a7c0d1c00900"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Circle"",
                    ""type"": ""Button"",
                    ""id"": ""b305c41c-f128-412b-bec2-21dc3cf8fdf5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Triangle"",
                    ""type"": ""Button"",
                    ""id"": ""900257a9-19e2-4a42-aa5e-36633a0e83fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Square"",
                    ""type"": ""Button"",
                    ""id"": ""56eb42df-c638-4336-9626-2d19083c7d97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f41841b7-c6b6-4170-b9e8-125e2ba9efd2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a85405aa-6162-421f-a09c-662f95fe97f1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""61a20062-8087-4564-9d41-2b9aba04814c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""596bdc14-5160-4f9d-a379-5e1ef45a395f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""36196fc9-16bc-4069-a3dc-67ef3ed57b7e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""269e7c7d-5cdc-4703-a9dc-f85ff114e1d2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3f07c8c4-3398-441e-8af3-2c503612ef23"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""143beba1-a47a-4353-bb02-4fc90c08eb95"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4c22a68f-b547-4310-812f-33c58d8e5ece"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e7656b3b-67ec-4ded-ad9e-8a3a3aa184a6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9fbff107-294d-470a-8e99-a6984c5e8011"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""715c57b7-bfa3-4437-9d1b-beb7fd33f877"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83da70b3-5ff2-468c-97e8-e815e4317959"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bea3f45-aa1f-40d6-8cbf-f020601756f4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17341d52-4b06-4059-a283-43727e799a27"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7475eb34-9706-4569-bf27-610bdd879c08"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""L2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac2b6290-5f69-44f1-a8b0-7b8d7bac8b1b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7dcd1b6-76e6-45ed-ba70-ce10fe3b3804"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2d99ae3-b976-40f1-a2aa-6e1688874116"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86c03766-6270-4f8c-965d-aebe2faab413"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e2e1f67-4c18-4f17-b52c-c1bca5789ece"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""R2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6615c809-0b4e-42fc-b88c-41f4cc629433"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c73463e-8669-4489-9896-5f76d8d9e9cd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Circle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1c92841-7795-4800-86bb-f3e5cf17c8f1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Triangle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""176d7ba4-535e-47fa-a1be-7930edd73166"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Square"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_LeftStick = m_Keyboard.FindAction("LeftStick", throwIfNotFound: true);
        m_Keyboard_RightStick = m_Keyboard.FindAction("RightStick", throwIfNotFound: true);
        m_Keyboard_Action = m_Keyboard.FindAction("Action", throwIfNotFound: true);
        m_Keyboard_Start = m_Keyboard.FindAction("Start", throwIfNotFound: true);
        m_Keyboard_Select = m_Keyboard.FindAction("Select", throwIfNotFound: true);
        m_Keyboard_DPadUp = m_Keyboard.FindAction("DPadUp", throwIfNotFound: true);
        m_Keyboard_DPadDown = m_Keyboard.FindAction("DPadDown", throwIfNotFound: true);
        m_Keyboard_DPadLeft = m_Keyboard.FindAction("DPadLeft", throwIfNotFound: true);
        m_Keyboard_DPadRight = m_Keyboard.FindAction("DPadRight", throwIfNotFound: true);
        m_Keyboard_L1 = m_Keyboard.FindAction("L1", throwIfNotFound: true);
        m_Keyboard_L2 = m_Keyboard.FindAction("L2", throwIfNotFound: true);
        m_Keyboard_R1 = m_Keyboard.FindAction("R1", throwIfNotFound: true);
        m_Keyboard_R2 = m_Keyboard.FindAction("R2", throwIfNotFound: true);
        m_Keyboard_X = m_Keyboard.FindAction("X", throwIfNotFound: true);
        m_Keyboard_Circle = m_Keyboard.FindAction("Circle", throwIfNotFound: true);
        m_Keyboard_Triangle = m_Keyboard.FindAction("Triangle", throwIfNotFound: true);
        m_Keyboard_Square = m_Keyboard.FindAction("Square", throwIfNotFound: true);
        // DualShock4
        m_DualShock4 = asset.FindActionMap("DualShock4", throwIfNotFound: true);
        m_DualShock4_LeftStick = m_DualShock4.FindAction("LeftStick", throwIfNotFound: true);
        m_DualShock4_RightStick = m_DualShock4.FindAction("RightStick", throwIfNotFound: true);
        m_DualShock4_Action = m_DualShock4.FindAction("Action", throwIfNotFound: true);
        m_DualShock4_Start = m_DualShock4.FindAction("Start", throwIfNotFound: true);
        m_DualShock4_Select = m_DualShock4.FindAction("Select", throwIfNotFound: true);
        m_DualShock4_DPadUp = m_DualShock4.FindAction("DPadUp", throwIfNotFound: true);
        m_DualShock4_DPadDown = m_DualShock4.FindAction("DPadDown", throwIfNotFound: true);
        m_DualShock4_DPadLeft = m_DualShock4.FindAction("DPadLeft", throwIfNotFound: true);
        m_DualShock4_DPadRight = m_DualShock4.FindAction("DPadRight", throwIfNotFound: true);
        m_DualShock4_L1 = m_DualShock4.FindAction("L1", throwIfNotFound: true);
        m_DualShock4_L2 = m_DualShock4.FindAction("L2", throwIfNotFound: true);
        m_DualShock4_R1 = m_DualShock4.FindAction("R1", throwIfNotFound: true);
        m_DualShock4_R2 = m_DualShock4.FindAction("R2", throwIfNotFound: true);
        m_DualShock4_X = m_DualShock4.FindAction("X", throwIfNotFound: true);
        m_DualShock4_Circle = m_DualShock4.FindAction("Circle", throwIfNotFound: true);
        m_DualShock4_Triangle = m_DualShock4.FindAction("Triangle", throwIfNotFound: true);
        m_DualShock4_Square = m_DualShock4.FindAction("Square", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private IKeyboardActions m_KeyboardActionsCallbackInterface;
    private readonly InputAction m_Keyboard_LeftStick;
    private readonly InputAction m_Keyboard_RightStick;
    private readonly InputAction m_Keyboard_Action;
    private readonly InputAction m_Keyboard_Start;
    private readonly InputAction m_Keyboard_Select;
    private readonly InputAction m_Keyboard_DPadUp;
    private readonly InputAction m_Keyboard_DPadDown;
    private readonly InputAction m_Keyboard_DPadLeft;
    private readonly InputAction m_Keyboard_DPadRight;
    private readonly InputAction m_Keyboard_L1;
    private readonly InputAction m_Keyboard_L2;
    private readonly InputAction m_Keyboard_R1;
    private readonly InputAction m_Keyboard_R2;
    private readonly InputAction m_Keyboard_X;
    private readonly InputAction m_Keyboard_Circle;
    private readonly InputAction m_Keyboard_Triangle;
    private readonly InputAction m_Keyboard_Square;
    public struct KeyboardActions
    {
        private @InputScheme m_Wrapper;
        public KeyboardActions(@InputScheme wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftStick => m_Wrapper.m_Keyboard_LeftStick;
        public InputAction @RightStick => m_Wrapper.m_Keyboard_RightStick;
        public InputAction @Action => m_Wrapper.m_Keyboard_Action;
        public InputAction @Start => m_Wrapper.m_Keyboard_Start;
        public InputAction @Select => m_Wrapper.m_Keyboard_Select;
        public InputAction @DPadUp => m_Wrapper.m_Keyboard_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_Keyboard_DPadDown;
        public InputAction @DPadLeft => m_Wrapper.m_Keyboard_DPadLeft;
        public InputAction @DPadRight => m_Wrapper.m_Keyboard_DPadRight;
        public InputAction @L1 => m_Wrapper.m_Keyboard_L1;
        public InputAction @L2 => m_Wrapper.m_Keyboard_L2;
        public InputAction @R1 => m_Wrapper.m_Keyboard_R1;
        public InputAction @R2 => m_Wrapper.m_Keyboard_R2;
        public InputAction @X => m_Wrapper.m_Keyboard_X;
        public InputAction @Circle => m_Wrapper.m_Keyboard_Circle;
        public InputAction @Triangle => m_Wrapper.m_Keyboard_Triangle;
        public InputAction @Square => m_Wrapper.m_Keyboard_Square;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterface != null)
            {
                @LeftStick.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnLeftStick;
                @LeftStick.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnLeftStick;
                @LeftStick.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnLeftStick;
                @RightStick.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRightStick;
                @RightStick.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRightStick;
                @RightStick.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnRightStick;
                @Action.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAction;
                @Start.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSelect;
                @DPadUp.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadUp;
                @DPadUp.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadUp;
                @DPadUp.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadUp;
                @DPadDown.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadDown;
                @DPadDown.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadDown;
                @DPadDown.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadDown;
                @DPadLeft.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadLeft;
                @DPadRight.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadRight;
                @DPadRight.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadRight;
                @DPadRight.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnDPadRight;
                @L1.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnL2;
                @R1.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnR2;
                @X.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnX;
                @Circle.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnCircle;
                @Circle.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnCircle;
                @Circle.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnCircle;
                @Triangle.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnTriangle;
                @Triangle.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnTriangle;
                @Triangle.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnTriangle;
                @Square.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSquare;
                @Square.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSquare;
                @Square.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnSquare;
            }
            m_Wrapper.m_KeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftStick.started += instance.OnLeftStick;
                @LeftStick.performed += instance.OnLeftStick;
                @LeftStick.canceled += instance.OnLeftStick;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Circle.started += instance.OnCircle;
                @Circle.performed += instance.OnCircle;
                @Circle.canceled += instance.OnCircle;
                @Triangle.started += instance.OnTriangle;
                @Triangle.performed += instance.OnTriangle;
                @Triangle.canceled += instance.OnTriangle;
                @Square.started += instance.OnSquare;
                @Square.performed += instance.OnSquare;
                @Square.canceled += instance.OnSquare;
            }
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);

    // DualShock4
    private readonly InputActionMap m_DualShock4;
    private IDualShock4Actions m_DualShock4ActionsCallbackInterface;
    private readonly InputAction m_DualShock4_LeftStick;
    private readonly InputAction m_DualShock4_RightStick;
    private readonly InputAction m_DualShock4_Action;
    private readonly InputAction m_DualShock4_Start;
    private readonly InputAction m_DualShock4_Select;
    private readonly InputAction m_DualShock4_DPadUp;
    private readonly InputAction m_DualShock4_DPadDown;
    private readonly InputAction m_DualShock4_DPadLeft;
    private readonly InputAction m_DualShock4_DPadRight;
    private readonly InputAction m_DualShock4_L1;
    private readonly InputAction m_DualShock4_L2;
    private readonly InputAction m_DualShock4_R1;
    private readonly InputAction m_DualShock4_R2;
    private readonly InputAction m_DualShock4_X;
    private readonly InputAction m_DualShock4_Circle;
    private readonly InputAction m_DualShock4_Triangle;
    private readonly InputAction m_DualShock4_Square;
    public struct DualShock4Actions
    {
        private @InputScheme m_Wrapper;
        public DualShock4Actions(@InputScheme wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftStick => m_Wrapper.m_DualShock4_LeftStick;
        public InputAction @RightStick => m_Wrapper.m_DualShock4_RightStick;
        public InputAction @Action => m_Wrapper.m_DualShock4_Action;
        public InputAction @Start => m_Wrapper.m_DualShock4_Start;
        public InputAction @Select => m_Wrapper.m_DualShock4_Select;
        public InputAction @DPadUp => m_Wrapper.m_DualShock4_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_DualShock4_DPadDown;
        public InputAction @DPadLeft => m_Wrapper.m_DualShock4_DPadLeft;
        public InputAction @DPadRight => m_Wrapper.m_DualShock4_DPadRight;
        public InputAction @L1 => m_Wrapper.m_DualShock4_L1;
        public InputAction @L2 => m_Wrapper.m_DualShock4_L2;
        public InputAction @R1 => m_Wrapper.m_DualShock4_R1;
        public InputAction @R2 => m_Wrapper.m_DualShock4_R2;
        public InputAction @X => m_Wrapper.m_DualShock4_X;
        public InputAction @Circle => m_Wrapper.m_DualShock4_Circle;
        public InputAction @Triangle => m_Wrapper.m_DualShock4_Triangle;
        public InputAction @Square => m_Wrapper.m_DualShock4_Square;
        public InputActionMap Get() { return m_Wrapper.m_DualShock4; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DualShock4Actions set) { return set.Get(); }
        public void SetCallbacks(IDualShock4Actions instance)
        {
            if (m_Wrapper.m_DualShock4ActionsCallbackInterface != null)
            {
                @LeftStick.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnLeftStick;
                @LeftStick.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnLeftStick;
                @LeftStick.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnLeftStick;
                @RightStick.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnRightStick;
                @RightStick.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnRightStick;
                @RightStick.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnRightStick;
                @Action.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnAction;
                @Start.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnStart;
                @Start.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnStart;
                @Start.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnStart;
                @Select.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSelect;
                @DPadUp.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadUp;
                @DPadUp.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadUp;
                @DPadUp.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadUp;
                @DPadDown.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadDown;
                @DPadDown.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadDown;
                @DPadDown.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadDown;
                @DPadLeft.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadLeft;
                @DPadLeft.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadLeft;
                @DPadRight.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadRight;
                @DPadRight.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadRight;
                @DPadRight.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnDPadRight;
                @L1.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL1;
                @L1.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL1;
                @L1.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL1;
                @L2.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL2;
                @L2.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL2;
                @L2.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnL2;
                @R1.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR1;
                @R1.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR1;
                @R1.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR1;
                @R2.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR2;
                @R2.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR2;
                @R2.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnR2;
                @X.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnX;
                @Circle.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnCircle;
                @Circle.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnCircle;
                @Circle.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnCircle;
                @Triangle.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnTriangle;
                @Triangle.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnTriangle;
                @Triangle.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnTriangle;
                @Square.started -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSquare;
                @Square.performed -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSquare;
                @Square.canceled -= m_Wrapper.m_DualShock4ActionsCallbackInterface.OnSquare;
            }
            m_Wrapper.m_DualShock4ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftStick.started += instance.OnLeftStick;
                @LeftStick.performed += instance.OnLeftStick;
                @LeftStick.canceled += instance.OnLeftStick;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
                @L1.started += instance.OnL1;
                @L1.performed += instance.OnL1;
                @L1.canceled += instance.OnL1;
                @L2.started += instance.OnL2;
                @L2.performed += instance.OnL2;
                @L2.canceled += instance.OnL2;
                @R1.started += instance.OnR1;
                @R1.performed += instance.OnR1;
                @R1.canceled += instance.OnR1;
                @R2.started += instance.OnR2;
                @R2.performed += instance.OnR2;
                @R2.canceled += instance.OnR2;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Circle.started += instance.OnCircle;
                @Circle.performed += instance.OnCircle;
                @Circle.canceled += instance.OnCircle;
                @Triangle.started += instance.OnTriangle;
                @Triangle.performed += instance.OnTriangle;
                @Triangle.canceled += instance.OnTriangle;
                @Square.started += instance.OnSquare;
                @Square.performed += instance.OnSquare;
                @Square.canceled += instance.OnSquare;
            }
        }
    }
    public DualShock4Actions @DualShock4 => new DualShock4Actions(this);
    public interface IKeyboardActions
    {
        void OnLeftStick(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnCircle(InputAction.CallbackContext context);
        void OnTriangle(InputAction.CallbackContext context);
        void OnSquare(InputAction.CallbackContext context);
    }
    public interface IDualShock4Actions
    {
        void OnLeftStick(InputAction.CallbackContext context);
        void OnRightStick(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnStart(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
        void OnL1(InputAction.CallbackContext context);
        void OnL2(InputAction.CallbackContext context);
        void OnR1(InputAction.CallbackContext context);
        void OnR2(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnCircle(InputAction.CallbackContext context);
        void OnTriangle(InputAction.CallbackContext context);
        void OnSquare(InputAction.CallbackContext context);
    }
}
